services:
  backend:
    build: ./backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "127.0.0.1:5000:5000"
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "127.0.0.1:4173:8080"
    depends_on:
      - backend

  postgres:
    image: bitnami/postgresql@sha256:e9d4bdd350e8446c630d84dfd56da4ab1c9779802d47d043948861eff452b895
    restart: always
    environment:
      - POSTGRESQL_USERNAME=${POSTGRES_USER}
      - POSTGRESQL_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRES_DB}
    volumes:
      - ./backend/models/:/docker-entrypoint-initdb.d/
      - postgres_data:/bitnami/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRESQL_USERNAME -d $$POSTGRESQL_DATABASE"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
